name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  native-linux-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build native image with Gradle
        run: |
          ./gradlew shadowJar nativeImage

      - name: Upload linux build
        uses: actions/upload-artifact@master
        with:
          name: native-image-linux
          path: build/graal/jiracli-linux-amd64
  
  native-macos-image:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build native image with Gradle
        run: |
          ./gradlew shadowJar nativeImage
          ls build/graal

      - name: Upload macos build
        uses: actions/upload-artifact@master
        with:
          name: native-image-macos
          path: build/graal/macos-amd64

  release:
    runs-on: ubuntu-latest
    needs: [native-linux-image, native-macos-image]
    steps:
      - uses: actions/checkout@v1

      - name: Download linux artifact
        uses: actions/download-artifact@master
        with:
          name: native-image-linux

      - name: Download macos artifact
        uses: actions/download-artifact@master
        with:
          name: native-image-macos

      - name: GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            RELEASE-NOTES.md
            native-image-linux/jiracli-linux-amd64
            native-image-macos/macos-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}